#!/usr/bin/env python3
"""Verify ignored Capacitor/Cordova Android build inputs against the locked CLI (NEW-002).

Tracked `android-app/android/settings.gradle` and `app/capacitor.build.gradle` require the
git-ignored `capacitor-cordova-android-plugins/` Gradle module, and Gradle packages other
ignored generated files (plugin registry, Cordova config, WebView `cordova*.js`). A clean
checkout lacks them, and a stale or altered tree can silently build outdated plugin wiring,
extra `src/main/libs` JARs, or WebView scripts. This read-only preflight regenerates, in
memory, what `npx cap sync android` from the installed, lock-matched @capacitor/cli writes for
the current configuration, and fails closed on any missing, extra or different input.

It models @capacitor/cli 8.5.0 (dist/android/update.js, dist/cordova.js) for a Capacitor-only
project: no Cordova plugins, no includePlugins, no Cordova preferences/access origins and a
JSON Capacitor config. Anything else fails closed and needs re-review.

It does not verify the Gradle dependency cache used by `--offline`.
Bootstrap: cd android-app && npm ci && npx cap sync android
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tarfile
from pathlib import Path

SUPPORTED_CLI = "8.5.0"
CLI_MIN_SDK = "24"
HEADER = '// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN'
BOOTSTRAP = "cd android-app && npm ci && npx cap sync android"
MODULE = "capacitor-cordova-android-plugins"
TEMPLATE = "node_modules/@capacitor/cli/assets/capacitor-cordova-android-plugins.tar.gz"
GRADLE_OUTPUT_DIRS = {"build", ".gradle"}
CLASS_RE = re.compile(r"^@(?:CapacitorPlugin|NativePlugin)[\s\S]+?class ([\w]+)", re.M)
PACKAGE_RE = re.compile(r"^package ([\w.]+);?$", re.M)


class GeneratedInputError(RuntimeError):
    pass


def fail(message: str):
    raise GeneratedInputError(message)


def text(path: Path) -> str:
    if not path.is_file():
        fail(f"missing required input: {path}")
    # Generated files are written with LF; a Windows checkout may convert tracked files.
    return path.read_bytes().decode("utf-8").replace("\r\n", "\n")


def load_json(path: Path):
    try:
        return json.loads(text(path))
    except json.JSONDecodeError as error:
        fail(f"invalid JSON in {path}: {error}")


def same(path: Path, expected: str, label: str) -> None:
    if text(path) != expected:
        fail(f"{label} differs from what the locked Capacitor CLI generates: {path}")


def rel(target: Path, start: Path) -> str:
    return Path(os.path.relpath(target, start)).as_posix()


def gradle_name(plugin_id: str) -> str:
    # JavaScript String.replace with a string pattern replaces only the first occurrence.
    return plugin_id.replace("@", "", 1).replace("/", "-", 1)


def resolve_plugins(app: Path, package: dict, lock: dict) -> list[dict]:
    packages = lock.get("packages")
    if not isinstance(packages, dict):
        fail("package-lock.json has no packages map; lockfileVersion 2 or later is required")
    names = list(package.get("dependencies") or {}) + list(package.get("devDependencies") or {})
    plugins = []
    for name in names:
        root = app / "node_modules" / name
        if not (root / "package.json").is_file():
            fail(f"dependency {name} is not installed; run npm ci")
        meta = load_json(root / "package.json")
        locked = packages.get(f"node_modules/{name}") or {}
        if not locked.get("version") or meta.get("version") != locked["version"]:
            fail(f"installed {name}@{meta.get('version')} does not match package-lock.json "
                 f"({locked.get('version')}); run npm ci")
        manifest = meta.get("capacitor")
        if manifest:
            android = manifest.get("android") if isinstance(manifest, dict) else None
            if not android:
                continue
            src = android.get("src") or "android"
            path = f"android/{name}" if (root / src / name).exists() else Path(src).as_posix()
            plugins.append({"id": name, "root": root, "path": path})
        elif (root / "plugin.xml").is_file():
            fail(f"{name} is a Cordova plugin; generated Cordova inputs need a new review")
    return plugins


def plugin_classes(plugin: dict) -> set[str]:
    source = plugin["root"] / plugin["path"] / "src" / "main"
    classes = set()
    if not source.is_dir():
        return classes
    for file in sorted(source.rglob("*")):
        if not file.is_file() or file.suffix not in (".java", ".kt"):
            continue
        content = file.read_text(encoding="utf-8")
        match = CLASS_RE.search(content)
        if match:
            package = PACKAGE_RE.search(content[:match.start()])
            if not package:
                fail(f"package could not be parsed from Android plugin: {file}")
            classes.add(f"{package.group(1)}.{match.group(1)}")
    return classes


def verify(root: Path) -> list[str]:
    app = root / "android-app"
    android = app / "android"
    main = android / "app" / "src" / "main"
    module = android / MODULE

    for unsupported in ("capacitor.config.ts", "capacitor.config.js"):
        if (app / unsupported).exists():
            fail(f"{unsupported} is not supported by this preflight; use capacitor.config.json")
    config = load_json(app / "capacitor.config.json")
    if "includePlugins" in config or "includePlugins" in (config.get("android") or {}):
        fail("includePlugins is not supported by this preflight")
    if "cordova" in config:
        fail("Cordova preferences/access origins are not supported by this preflight")

    package = load_json(app / "package.json")
    lock = load_json(app / "package-lock.json")
    plugins = resolve_plugins(app, package, lock)
    cli = load_json(app / "node_modules/@capacitor/cli/package.json")
    if cli.get("version") != SUPPORTED_CLI:
        fail(f"@capacitor/cli {cli.get('version')} is not the reviewed {SUPPORTED_CLI}")
    if f"minVersion: '{CLI_MIN_SDK}'" not in text(app / "node_modules/@capacitor/cli/dist/config.js"):
        fail("@capacitor/cli Android minVersion changed; re-review generated inputs")

    # Tracked Capacitor Gradle wiring (installGradlePlugins).
    settings = (f"{HEADER}\ninclude ':capacitor-android'\n"
                f"project(':capacitor-android').projectDir = new File("
                f"'{rel(app / 'node_modules/@capacitor/android/capacitor', android)}')\n")
    for plugin in plugins:
        name = gradle_name(plugin["id"])
        settings += (f"\ninclude ':{name}'\nproject(':{name}').projectDir = new File("
                     f"'{rel(plugin['root'], android)}/{plugin['path']}')\n")
    same(android / "capacitor.settings.gradle", settings, "capacitor.settings.gradle")
    implementations = "\n".join(f"    implementation project(':{gradle_name(p['id'])}')" for p in plugins)
    build = (f"{HEADER}\n\nandroid {{\n  compileOptions {{\n"
             "      sourceCompatibility JavaVersion.VERSION_21\n"
             "      targetCompatibility JavaVersion.VERSION_21\n  }\n}\n\n"
             f'apply from: "../{MODULE}/cordova.variables.gradle"\n'
             f"dependencies {{\n{implementations}\n\n}}\n\n\n"
             "if (hasProperty('postBuildExtras')) {\n  postBuildExtras()\n}\n")
    same(android / "app" / "capacitor.build.gradle", build, "app/capacitor.build.gradle")

    # Ignored Cordova plugin Gradle module (template + handleCordovaPluginsGradle + manifest).
    template_path = app / TEMPLATE
    if not template_path.is_file():
        fail(f"missing Capacitor CLI template: {template_path}")
    with tarfile.open(template_path, "r:gz") as archive:
        template = {m.name: archive.extractfile(m).read() for m in archive.getmembers() if m.isfile()}
    expected_files = set(template) | {"cordova.variables.gradle"}
    if not module.is_dir():
        fail(f"missing generated Cordova plugin module: {module}")
    actual_files = {
        path.relative_to(module).as_posix()
        for path in module.rglob("*")
        if path.is_file() and path.relative_to(module).parts[0] not in GRADLE_OUTPUT_DIRS
    }
    if actual_files != expected_files:
        fail(f"{MODULE} file set differs: missing {sorted(expected_files - actual_files)}, "
             f"unexpected {sorted(actual_files - expected_files)}")
    gradle = template["build.gradle"].decode("utf-8").replace("\r\n", "\n")
    gradle, first = re.subn(r"(SUB-PROJECT DEPENDENCIES START)[\s\S]*(// SUB-PROJECT DEPENDENCIES END)",
                            lambda m: m.group(1) + "\n\n    " + m.group(2), gradle, count=1)
    gradle, second = re.subn(r"(PLUGIN GRADLE EXTENSIONS START)[\s\S]*(// PLUGIN GRADLE EXTENSIONS END)",
                             lambda m: m.group(1) + '\napply from: "cordova.variables.gradle"\n' + m.group(2),
                             gradle, count=1)
    if (first, second) != (1, 1):
        fail("Capacitor CLI Cordova module template changed; re-review generated inputs")
    same(module / "build.gradle", gradle, f"{MODULE}/build.gradle")
    same(module / "cordova.variables.gradle",
         f"{HEADER}\next {{\n  cdvMinSdkVersion = project.hasProperty('minSdkVersion') ? "
         f"rootProject.ext.minSdkVersion : {CLI_MIN_SDK}\n"
         "  // Plugin gradle extensions can append to this to have code run at the end.\n"
         "  cdvPluginPostBuildExtras = []\n  cordovaConfig = [:]\n}",
         f"{MODULE}/cordova.variables.gradle")
    cleartext = 'android:usesCleartextTraffic="true"' if (config.get("server") or {}).get("cleartext") else ""
    same(module / "src/main/AndroidManifest.xml",
         "<?xml version='1.0' encoding='utf-8'?>\n"
         '<manifest xmlns:android="http://schemas.android.com/apk/res/android"\n'
         'xmlns:amazon="http://schemas.amazon.com/apk/res/android">\n'
         f"<application  {cleartext}>\n\n</application>\n\n</manifest>",
         f"{MODULE}/src/main/AndroidManifest.xml")
    for name in template:
        if name.endswith(".gitkeep") and (module / name).read_bytes() != template[name]:
            fail(f"{MODULE}/{name} differs from the CLI template")

    # Packaged generated assets and resources.
    registry = load_json(main / "assets" / "capacitor.plugins.json")
    expected_registry = [(p["id"], plugin_classes(p)) for p in plugins]
    expected_registry = [(pid, classes) for pid, classes in expected_registry if classes]
    if (not isinstance(registry, list)
            or any(not isinstance(e, dict) or set(e) != {"pkg", "classpath"} for e in registry)):
        fail("capacitor.plugins.json has an unexpected structure")
    order = []
    for entry in registry:
        if not order or order[-1] != entry["pkg"]:
            order.append(entry["pkg"])
    actual_registry = [(pid, {e["classpath"] for e in registry if e["pkg"] == pid}) for pid in order]
    if actual_registry != expected_registry or len(registry) != sum(len(c) for _, c in expected_registry):
        fail("capacitor.plugins.json does not match the installed Capacitor plugins")
    if load_json(main / "assets" / "capacitor.config.json") != config:
        fail("packaged capacitor.config.json differs from android-app/capacitor.config.json")
    same(main / "res" / "xml" / "config.xml",
         "<?xml version='1.0' encoding='utf-8'?>\n"
         '<widget version="1.0.0" xmlns="http://www.w3.org/ns/widgets" '
         'xmlns:cdv="http://cordova.apache.org/ns/1.0">\n'
         '  <access origin="*" />\n  \n  \n</widget>',
         "res/xml/config.xml")
    public = main / "assets" / "public"
    for name in ("cordova.js", "cordova_plugins.js"):
        path = public / name
        if not path.is_file():
            fail(f"missing generated WebView script: {path}")
        if path.stat().st_size != 0:
            fail(f"generated WebView script must be empty without Cordova plugins: {path}")
    if (public / "plugins").exists():
        fail(f"unexpected Cordova plugin web directory: {public / 'plugins'}")

    return [p["id"] for p in plugins]


def main() -> int:
    parser = argparse.ArgumentParser(description="Verify generated Android build inputs (NEW-002)")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    try:
        plugins = verify(args.root.resolve())
    except (GeneratedInputError, OSError, UnicodeDecodeError, tarfile.TarError) as error:
        print(f"FAIL: {error}", file=sys.stderr)
        print(f"Regenerate from the locked tree, review the result, then retry: {BOOTSTRAP}", file=sys.stderr)
        return 1
    print(f"generated Android inputs OK: @capacitor/cli {SUPPORTED_CLI}, {len(plugins)} Capacitor plugins, "
          "0 Cordova plugins")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
